### PR TITLE
Quickhack squelch false positives

### PR DESCRIPTION
**Pull request by aaronkaplan**
this needs to be reviewed on Monday / Tuesday

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
We have the `squelcher.conf` for this purpose.

**Comment by aaronkaplan** [comment]
After re-discussions today, we decided that this is *not* the case for the extra field.
See issue #122.
So, this quick hack goes through for now but we will have to re-visit and re-do this in a better squelcher bot in the future.

**Comment by aaronkaplan** [comment]
@wagner-certat can you confirme this PR and let's merge it? 
It works in the installation now.

**Comment by ghost** [comment]
For reference: certtools/intelmq#793 (concerning usage of extra)

**Pull request merged**
